name = "page"
compatibility_date = "2026-06-18"
compatibility_flags = ["global_fetch_strictly_public", "nodejs_compat"]

"main" = "@astrojs/cloudflare/entrypoints/server"

[[routes]]
pattern = "omu-aikido.com"
custom_domain = true

[placement]
mode = "smart"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

[secrets]
required = ["CF_TURNSTILE_SECRETKEY", "DISCORD_WEBHOOK_URL"]

[ai]
binding = "AI"
remote = true

[[send_email]]
destination_address = "aikido.omu@gmail.com"
remote = true
name = "CONTACT_MAILER"
