name = "page"
compatibility_date = "2026-06-18"
compatibility_flags = ["global_fetch_strictly_public", "nodejs_compat"]

main = ".output/server/index.mjs"

[[routes]]
pattern = "omu-aikido.com"
custom_domain = true

[placement]
mode = "smart"

[assets]
directory = ".output/public"
binding = "ASSETS"
html_handling = "drop-trailing-slash"

[observability.logs]
enabled = true
invocation_logs = false

[observability.traces]
enabled = true

[secrets]
required = ["CF_TURNSTILE_SECRETKEY", "DISCORD_WEBHOOK_URL"]

[vars]
CONTACT_ALLOWED_ORIGINS = "https://omu-aikido.com"
TURNSTILE_HOSTNAME = "omu-aikido.com"

[ai]
binding = "AI"
remote = true

[[send_email]]
destination_address = "aikido.omu@gmail.com"
remote = true
name = "CONTACT_MAILER"

[[ratelimits]]
name = "CONTACT_RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 10
period = 60
