import { mkdir, readFile, writeFile } from "node:fs/promises";
import { marked } from "marked";

const files = [
  ["/about/aikido", "content/pages/about/aikido.md"],
  ["/about/links", "content/pages/about/links.md"],
  ["/privacy-policy", "content/pages/privacy-policy.md"],
  ["/support", "content/pages/support.md"],
  ["/terms-of-service", "content/pages/terms-of-service.md"],
] as const;
const title = "# 大阪公立大学合氣道部";
const intro =
  "大阪公立大学で活動する体育会所属の合気道団体、大阪公立大学合氣道部の公式情報です。";

function parseFrontmatter(source: string) {
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(source);
  const metadata: Record<string, string> = {};
  for (const line of match?.[1]?.split("\n") ?? []) {
    const separator = line.indexOf(":");
    if (separator > 0) {
      metadata[line.slice(0, separator).trim()] = line
        .slice(separator + 1)
        .trim();
    }
  }
  return { metadata, markdown: (match?.[2] ?? source).trim() };
}

function renderMarkdown(markdown: string) {
  return (marked.parse(markdown) as string)
    .replace(
      /<a href="(https?:\/\/[^"]+)">/g,
      '<a href="$1" target="_blank" rel="noopener noreferrer" class="outer_link">',
    )
    .replace(/<a href="(\/[^"]*)">/g, '<a href="$1" class="link">');
}

const pages = await Promise.all(
  files.map(async ([path, filename]) => {
    const parsed = parseFrontmatter(await readFile(filename, "utf8"));
    return {
      path,
      title: parsed.metadata.title ?? "",
      description: parsed.metadata.description ?? "",
      markdown: parsed.markdown,
      html: renderMarkdown(parsed.markdown),
    };
  }),
);
const links = pages
  .map((page) => `- [${page.path}](https://omu-aikido.com${page.path})`)
  .join("\n");
const index = `${title}\n\n${intro}\n\n## Pages\n\n${links}\n`;
const small = `${title}\n\n${intro}\n\n${pages
  .map(
    (page) =>
      `## ${page.path}\n\n${page.markdown
        .split("\n")
        .filter((line) => line.startsWith("#"))
        .join("\n")}`,
  )
  .join("\n\n")}\n`;
const full = `${title}\n\n${intro}\n\n${pages
  .map((page) => `## ${page.path}\n\n${page.markdown}`)
  .join("\n\n")}\n`;
const generated = Object.fromEntries(
  pages.map((page) => [
    page.path,
    { title: page.title, description: page.description, html: page.html },
  ]),
);

await mkdir("app/generated", { recursive: true });
await Promise.all([
  writeFile("public/llms.txt", index),
  writeFile("public/llms-small.txt", small),
  writeFile("public/llms-full.txt", full),
  writeFile(
    "app/generated/content.ts",
    `// Generated by scripts/generate-site-content.ts.\nexport const generatedContent = ${JSON.stringify(generated, null, 2)} as const;\n`,
  ),
]);
