name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Install dependencies
        run: nix-shell -p bun --run "bun install"

      - name: Lint code
        run: nix-shell -p bun --run "bun run lint"

      - name: Format code
        run: nix-shell -p bun --run "bun run format"

      - name: Build project
        run: nix-shell -p bun --run "bun run build"